# Generated by Django 5.2.17 on 2026-09-03 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='studentguardian',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('student',), name='unique_primary_guardian_per_student'),
        ),
    ]
