# Generated by Django 5.2.17 on 2026-09-02 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('FOR_REVIEW', 'For Review'), ('CONTACTING_PARENT', 'Contacting Parent'), ('MEETING_SCHEDULED', 'Meeting Scheduled'), ('HOME_VISIT_SCHEDULED', 'Home Visit Scheduled'), ('UNDER_INTERVENTION', 'Under Intervention'), ('FOR_FOLLOW_UP', 'For Follow-up'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='FOR_REVIEW', max_length=30)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('findings', models.TextField(blank=True)),
                ('follow_up_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_interventions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intervention_cases', to='students.student')),
            ],
        ),
    ]
