# Generated by Django 5.2.17 on 2026-09-02 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('recipient_masked', models.CharField(max_length=30)),
                ('event_key', models.CharField(help_text='Prevents duplicate messages for one event.', max_length=150, unique=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='QUEUED', max_length=15)),
                ('provider_reference', models.CharField(blank=True, max_length=100)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sms_logs', to='students.guardian')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sms_logs', to='students.student')),
            ],
        ),
    ]
