# Generated by Django 5.2.17 on 2026-09-02 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT_EXCUSED', 'Excused Absence'), ('ABSENT_UNEXCUSED', 'Unexcused Absence'), ('SCHOOL_ACTIVITY', 'School Activity'), ('NOT_RECORDED', 'Not Recorded')], db_index=True, default='NOT_RECORDED', max_length=25)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('excuse_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='academics.classschedule')),
                ('encoded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encoded_attendance', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='students.student')),
            ],
            options={
                'ordering': ('-date', 'student__last_name'),
                'constraints': [models.UniqueConstraint(fields=('student', 'class_schedule', 'date'), name='unique_student_schedule_attendance')],
            },
        ),
    ]
